apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: Python app that displays time - named test
  annotations:
    github.com/project-slug: divakaivan-org/test
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental